import { FabricSpecs, YarnRates, WeavingCharges, Commercials } from "./types";

export interface FabricPreset {
  id: string;
  name: string;
  category: string;
  description: string;
  specs: FabricSpecs;
  yarnRates: YarnRates;
  weavingCharges: WeavingCharges;
  commercials: Commercials;
}

export const FABRIC_PRESETS: FabricPreset[] = [
  {
    id: "poplin-40-40",
    name: "Classic Poplin 40x40 / 133x72",
    category: "Shirting & Apparel",
    description: "Standard 100% Combed Cotton Poplin greige fabric for premium dress shirts and fashion apparel.",
    specs: {
      qualityName: "Cotton Poplin 40x40 133x72",
      buyerName: "Global Apparel Brands",
      warpCount: 40,
      warpPly: 1,
      warpBlend: "100% Combed Cotton",
      weftCount: 40,
      weftPly: 1,
      weftBlend: "100% Combed Cotton",
      epi: 133,
      ppi: 72,
      reedSpace: 67,
      greigeWidth: 63,
      finishedWidth: 58,
      warpCrimp: 6.5,
      weftCrimp: 4.0,
      selvedgeEnds: 48,
      weaveType: "Plain (1/1)",
    },
    yarnRates: {
      warpRatePerKg: 4.10,
      weftRatePerKg: 3.95,
      warpWastagePercent: 2.5,
      weftWastagePercent: 3.0,
      sizingChemicalCostPerKg: 0.35,
      sizingWastagePercent: 1.0,
    },
    weavingCharges: {
      loomType: "Airjet",
      loomRpm: 800,
      loomEfficiency: 90,
      chargeMethod: "perPick",
      ratePerPick: 0.0075,
      chargePerMeter: 0.54,
      powerCostPerMeter: 0.08,
      laborCostPerMeter: 0.06,
      maintenanceCostPerMeter: 0.04,
      fixedOverheadsPerMeter: 0.07,
      inspectionMendingPerMeter: 0.03,
      foldingPackingPerMeter: 0.04,
    },
    commercials: {
      profitMarginPercent: 12.0,
      orderQuantityMeters: 25000,
      currency: "USD",
      paymentTerms: "LC at sight 60 Days",
      deliveryWeeks: 4,
      targetPricePerMeter: 1.85,
    },
  },
  {
    id: "sheeting-30-30",
    name: "Standard Sheeting 30x30 / 68x68",
    category: "Home Textiles",
    description: "High volume plain weave sheeting for bed sheets, pillowcases, and home furnishing greige.",
    specs: {
      qualityName: "Cotton Sheeting 30x30 68x68",
      buyerName: "Home Comfort Retail",
      warpCount: 30,
      warpPly: 1,
      warpBlend: "100% Carded Cotton",
      weftCount: 30,
      weftPly: 1,
      weftBlend: "100% Carded Cotton",
      epi: 68,
      ppi: 68,
      reedSpace: 66,
      greigeWidth: 63,
      finishedWidth: 60,
      warpCrimp: 5.5,
      weftCrimp: 4.5,
      selvedgeEnds: 40,
      weaveType: "Plain (1/1)",
    },
    yarnRates: {
      warpRatePerKg: 3.50,
      weftRatePerKg: 3.40,
      warpWastagePercent: 2.0,
      weftWastagePercent: 2.5,
      sizingChemicalCostPerKg: 0.28,
      sizingWastagePercent: 1.0,
    },
    weavingCharges: {
      loomType: "Airjet",
      loomRpm: 850,
      loomEfficiency: 92,
      chargeMethod: "perPick",
      ratePerPick: 0.0068,
      chargePerMeter: 0.46,
      powerCostPerMeter: 0.06,
      laborCostPerMeter: 0.05,
      maintenanceCostPerMeter: 0.03,
      fixedOverheadsPerMeter: 0.05,
      inspectionMendingPerMeter: 0.02,
      foldingPackingPerMeter: 0.03,
    },
    commercials: {
      profitMarginPercent: 10.0,
      orderQuantityMeters: 50000,
      currency: "USD",
      paymentTerms: "LC at 30 Days",
      deliveryWeeks: 5,
      targetPricePerMeter: 1.30,
    },
  },
  {
    id: "twill-20-16",
    name: "Heavy Chino Twill 2/1 20x16 / 108x56",
    category: "Bottomweight & Workwear",
    description: "Rugged 2/1 twill fabric ideal for khaki trousers, cargo pants, uniforms, and workwear.",
    specs: {
      qualityName: "Cotton Twill 2/1 20x16 108x56",
      buyerName: "Industrial Workwear Corp",
      warpCount: 20,
      warpPly: 1,
      warpBlend: "100% Ring Spun Cotton",
      weftCount: 16,
      weftPly: 1,
      weftBlend: "100% Ring Spun Cotton",
      epi: 108,
      ppi: 56,
      reedSpace: 67,
      greigeWidth: 63,
      finishedWidth: 58,
      warpCrimp: 8.0,
      weftCrimp: 5.0,
      selvedgeEnds: 56,
      weaveType: "Twill (2/1)",
    },
    yarnRates: {
      warpRatePerKg: 3.25,
      weftRatePerKg: 3.10,
      warpWastagePercent: 2.8,
      weftWastagePercent: 3.2,
      sizingChemicalCostPerKg: 0.32,
      sizingWastagePercent: 1.2,
    },
    weavingCharges: {
      loomType: "Rapier",
      loomRpm: 550,
      loomEfficiency: 88,
      chargeMethod: "perPick",
      ratePerPick: 0.009,
      chargePerMeter: 0.50,
      powerCostPerMeter: 0.09,
      laborCostPerMeter: 0.07,
      maintenanceCostPerMeter: 0.05,
      fixedOverheadsPerMeter: 0.08,
      inspectionMendingPerMeter: 0.04,
      foldingPackingPerMeter: 0.05,
    },
    commercials: {
      profitMarginPercent: 14.0,
      orderQuantityMeters: 20000,
      currency: "USD",
      paymentTerms: "TT 30% advance, 70% against BL",
      deliveryWeeks: 4,
      targetPricePerMeter: 2.15,
    },
  },
  {
    id: "satin-60-60",
    name: "Luxury Bed Satin 4/1 60x60 / 173x120",
    category: "Luxury Bedding",
    description: "Ultra-fine high thread count 300+ TC satin weave for 5-star hotel and luxury bedding collections.",
    specs: {
      qualityName: "Cotton Satin 4/1 60x60 173x120",
      buyerName: "Prestige Hospitality Linen",
      warpCount: 60,
      warpPly: 1,
      warpBlend: "100% Extra Long Staple Cotton",
      weftCount: 60,
      weftPly: 1,
      weftBlend: "100% Extra Long Staple Cotton",
      epi: 173,
      ppi: 120,
      reedSpace: 126,
      greigeWidth: 120,
      finishedWidth: 114,
      warpCrimp: 7.0,
      weftCrimp: 5.5,
      selvedgeEnds: 64,
      weaveType: "Satin (4/1)",
    },
    yarnRates: {
      warpRatePerKg: 5.80,
      weftRatePerKg: 5.60,
      warpWastagePercent: 3.0,
      weftWastagePercent: 3.5,
      sizingChemicalCostPerKg: 0.45,
      sizingWastagePercent: 1.5,
    },
    weavingCharges: {
      loomType: "Airjet",
      loomRpm: 680,
      loomEfficiency: 86,
      chargeMethod: "perPick",
      ratePerPick: 0.011,
      chargePerMeter: 1.32,
      powerCostPerMeter: 0.16,
      laborCostPerMeter: 0.12,
      maintenanceCostPerMeter: 0.08,
      fixedOverheadsPerMeter: 0.14,
      inspectionMendingPerMeter: 0.06,
      foldingPackingPerMeter: 0.08,
    },
    commercials: {
      profitMarginPercent: 15.0,
      orderQuantityMeters: 15000,
      currency: "USD",
      paymentTerms: "LC at sight",
      deliveryWeeks: 6,
      targetPricePerMeter: 4.80,
    },
  },
  {
    id: "denim-10-7",
    name: "Rigid Denim 3/1 10x7 / 72x44",
    category: "Denim & Jeans",
    description: "Heavyweight 12.5 oz authentic raw indigo warp greige denim for heritage jeans and jackets.",
    specs: {
      qualityName: "Classic 3/1 Heavy Denim 10x7",
      buyerName: "Authentic Denim Mills",
      warpCount: 10,
      warpPly: 1,
      warpBlend: "100% Ring Spun Indigo Slub",
      weftCount: 7,
      weftPly: 1,
      weftBlend: "100% Open End Cotton",
      epi: 72,
      ppi: 44,
      reedSpace: 68,
      greigeWidth: 64,
      finishedWidth: 59,
      warpCrimp: 11.0,
      weftCrimp: 6.0,
      selvedgeEnds: 60,
      weaveType: "Twill (3/1)",
    },
    yarnRates: {
      warpRatePerKg: 3.80,
      weftRatePerKg: 2.85,
      warpWastagePercent: 3.5,
      weftWastagePercent: 3.0,
      sizingChemicalCostPerKg: 0.38,
      sizingWastagePercent: 1.2,
    },
    weavingCharges: {
      loomType: "Rapier",
      loomRpm: 500,
      loomEfficiency: 85,
      chargeMethod: "perPick",
      ratePerPick: 0.0095,
      chargePerMeter: 0.42,
      powerCostPerMeter: 0.10,
      laborCostPerMeter: 0.08,
      maintenanceCostPerMeter: 0.06,
      fixedOverheadsPerMeter: 0.09,
      inspectionMendingPerMeter: 0.04,
      foldingPackingPerMeter: 0.06,
    },
    commercials: {
      profitMarginPercent: 12.5,
      orderQuantityMeters: 30000,
      currency: "USD",
      paymentTerms: "LC at 60 Days",
      deliveryWeeks: 5,
      targetPricePerMeter: 3.40,
    },
  },
  {
    id: "canvas-10-10",
    name: "Heavy Duck Canvas 10/2x10/2 / 48x32",
    category: "Heavy Industrial & Luggage",
    description: "High durability plied yarn duck canvas for tote bags, awnings, upholstery, and footwear.",
    specs: {
      qualityName: "Cotton Duck Canvas 10/2x10/2",
      buyerName: "Heritage Gear & Bag Co.",
      warpCount: 20,
      warpPly: 2,
      warpBlend: "100% Carded Cotton 2-Ply",
      weftCount: 20,
      weftPly: 2,
      weftBlend: "100% Carded Cotton 2-Ply",
      epi: 48,
      ppi: 32,
      reedSpace: 66,
      greigeWidth: 63,
      finishedWidth: 60,
      warpCrimp: 9.5,
      weftCrimp: 6.5,
      selvedgeEnds: 40,
      weaveType: "Canvas",
    },
    yarnRates: {
      warpRatePerKg: 3.65,
      weftRatePerKg: 3.55,
      warpWastagePercent: 2.2,
      weftWastagePercent: 2.8,
      sizingChemicalCostPerKg: 0.30,
      sizingWastagePercent: 1.0,
    },
    weavingCharges: {
      loomType: "Projectile (Sulzer)",
      loomRpm: 420,
      loomEfficiency: 86,
      chargeMethod: "perPick",
      ratePerPick: 0.012,
      chargePerMeter: 0.38,
      powerCostPerMeter: 0.11,
      laborCostPerMeter: 0.08,
      maintenanceCostPerMeter: 0.05,
      fixedOverheadsPerMeter: 0.08,
      inspectionMendingPerMeter: 0.04,
      foldingPackingPerMeter: 0.05,
    },
    commercials: {
      profitMarginPercent: 15.0,
      orderQuantityMeters: 18000,
      currency: "USD",
      paymentTerms: "Net 30 Days",
      deliveryWeeks: 4,
      targetPricePerMeter: 2.85,
    },
  },
];
